mappings:
  - language_name: Ukrainian Cyrillic
    display_name: Ukrainian Ukrainian to IPA
    in_lang: ukr-cyrl
    out_lang: ukr-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: ukr-Cyrl.csv
