mappings:
  - language_name: Punjabi (Eastern)
    display_name: Punjabi (Eastern) to IPA
    in_lang: pan
    out_lang: pan-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: pan-Guru.csv
