mappings:
  - language_name: Punjabi (Eastern)
    display_name: Punjabi (Eastern) to IPA
    in_lang: pun
    out_lang: pun-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: pun-Guru.csv
