mappings:
  - language_name: Tok Pisin Latin
    display_name: Tok Pisin Latin to IPA
    in_lang: tpi-latn
    out_lang: tuk-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: tpi-Latn.csv
