mappings:
  - language_name: Uzbek
    display_name: Uzbek to IPA
    in_lang: uzb
    out_lang: uzb-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: uzb-Latn.csv
  - language_name: Uzbek
    display_name: Uzbek to Cyrillic
    in_lang: uzb
    out_lang: uzb-cyrillic
    type: mapping
    authors:
      - David R. Mortensen
    mapping: uzb-Cyrl.csv
