mappings:
  - language_name: Uzbek Latin
    display_name: Uzbek Latin to IPA
    in_lang: uzb-latn
    out_lang: uzb-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: uzb-Latn.csv
  - language_name: Uzbek Cyrillic
    display_name: Uzbek Cyrillic to IPA
    in_lang: uzb-cyrl
    out_lang: uzb-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: uzb-Cyrl.csv
