mappings:
  - language_name: Tagalog Latin
    display_name: Tagalog to IPA
    in_lang: tgl-latn
    out_lang: tgl-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: tgl-Latn.csv
  - language_name: Tagalog Latin Reduced
    display_name: Tagalog to IPA
    in_lang: tgl-latn-red
    out_lang: tgl-ipa
    type: mapping
    authors:
      - David R. Mortensen
    mapping: tgl-Latn-red.csv
